#!/usr/bin/env ruby

=begin

OpenContrail checks (compat. with nagios exit codes)
Copyright (C) 2014  Sebastien Badia <sebastien.badia@enovance.com>
Sources and doc <https://github.com/sbadia/contrail-nagios/>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

=end

# If ruby 1.8 use rubygem
require 'rubygems' if RUBY_VERSION < '1.9.0'
# Contrail API return xml output
require 'rexml/document'
# Wrapper for net/{http,https}
require 'open-uri'
# For option managment
require 'ostruct'
require 'optparse'

# Monitoring return codes
OK        = 0
WARNING   = 1
CRITICAL  = 2
UNKNOWN   = 3
DEPENDENT = 4

# Script specific
PROG_NAME = File.basename($0)
PROG_VERSION   = '0.0.1'

req = nil
nodeok = 0

cfg = OpenStruct.new
OptionParser.new { |opts|
  opts.banner = "Usage: #{PROG_NAME} [options]"
  opts.summary_indent = '  '
  opts.version = PROG_VERSION
  opts.summary_width = 28
  opts.program_name = PROG_NAME
  opts.separator ''
  # default options
  cfg.verbose = false
  cfg.host = 'localhost'
  cfg.port = '8083'
  cfg.asn = false
  cfg.peertype = false
  cfg.peer = false

  opts.on('-H','--host', "Hostname to run on (default: #{cfg.host})") do
    cfg.host = ARGV[0]
  end
  opts.on('-p','--port',"controller API port (default: #{cfg.port})") do
    cfg.port = ARGV[0]
  end
  opts.on('-a','--peer-asn(s)',"Check only this peer ASN (default: #{cfg.asn})") do
    cfg.asn = ARGV[0]
  end
  opts.on('-t','--peer-type',"Check only this peer type (bgp/xmpp) (default: #{cfg.peertype})") do
    cfg.peertype = ARGV[0]
  end
  opts.on('-i','--peer-ip(s)',"Check only this peer IP (default: #{cfg.peer})") do
    cfg.peer = ARGV[0]
  end
  opts.on('-v','--verbose',"Display all messages (default: #{cfg.verbose})") do
    cfg.verbose = true
  end
  opts.on_tail('-h','--help','Display this help message') do
    puts opts
    exit OK
  end
}.parse!

begin
  open("http://#{cfg.host}:#{cfg.port}/Snh_BgpNeighborReq","User-Agent" => "#{PROG_NAME}/#{PROG_VERSION}") {|u| req = u.read }
rescue
  puts "CRITICAL: Could not connect to #{cfg.host}:#{cfg.port} (please check)"
  exit CRITICAL
end

def parse_contrail_xml(data)
  document = REXML::Document.new(data)
  bgp = Hash.new
  node = 0
  document.elements.each('//BgpNeighborResp') do |x|
    elements = x.elements
    bgp[node] = {
      :peer_address => elements['peer_address'].text,
      :state => elements['state'].text,
      :last_state => elements['last_state'].text,
      :last_state_at => elements['last_state_at'].text,
      :peer_asn => elements['peer_asn'].text,
      :encoding => elements['encoding'].text
    }
    node+=1
  end
  return bgp
end # def:: parse_contrail_xml(data)

def display_peer(data,nodeid)
  return "Peer with #{data[nodeid][:peer_address]} AS#{data[nodeid][:peer_asn]} (#{data[nodeid][:encoding]}) is #{data[nodeid][:state]} (last state #{data[nodeid][:last_state]} at #{data[nodeid][:last_state_at]})"
end # def:: display_peer(data,nodeid)

def isnt_number(n)
  false if Float(n) rescue true
end

def nagios_display(data,nodeid,ok)
  if isnt_number(nodeid)
    puts 'Please check your configuration'
    exit UNKNOWN
  end
  case data[nodeid][:state]
  when 'Established'
    puts "OK: #{display_peer(data,nodeid)}" if cfg.verbose
    ok+=1
  when 'OpenSent' || 'OpenConfirm'
    puts "WARNING: #{display_peer(data,nodeid)}"
  else
    puts "CRITICAL: #{display_peer(data,nodeid)}"
    # exit on the first critical connection
    exit CRITICAL
  end
  return ok
end # def:: nagios_display(data,nodeid)

def nagios_exit(length,numok,cfg)
  if cfg.ctrl or cfg.mcast
    length = 1
  elsif cfg.asn
    length = cfg.asn.split(',').length
  elsif cfg.peer
    length = cfg.peer.split(',').length
  end
  puts "[#{Time.now}] Peers connected #{numok}/#{length}"
  if numok == length
    exit OK
  elsif (numok < length and numok != 0)
    exit WARNING
  elsif numok == 0
    exit CRITICAL
  else
    exit UNKNOWN
  end
end # def:: nagios_exit(length,numok)

def select_node(data,key,value)
  data.each_key do |k|
    if data[k].has_key?(key)
      if data[k][key] == value
        return k
      end
    end
  end
end # def:: select_node(data,key,value)

def select_nodes(data,key,value)
  out = []
  data.each_key do |k|
    if data[k].has_key?(key)
      if data[k][key] == value
        out << k
      end
    end
  end
  return out
end

controller = parse_contrail_xml(req)

if cfg.asn
  cfg.asn.split(',').each do |as_number|
    nodeok=+nagios_display(controller,select_node(controller,:peer_asn,as_number),nodeok)
  end
  nagios_exit(controller.length,nodeok,cfg)
elsif cfg.peer
  cfg.peer.split(',').each do |peer_ip|
  nodeok=+nagios_display(controller,select_node(controller,:peer_address,peer_ip),nodeok)
  end
  nagios_exit(controller.length,nodeok,cfg)
elsif cfg.peertype
  peers = select_nodes(controller,:encoding,cfg.peertype.upcase)
  peers.each do |p|
    nodeok=+nagios_display(controller,p,nodeok)
  end
  nagios_exit(peers.length,nodeok,cfg)
else
  controller.each_key do |k|
    nodeok=+nagios_display(controller,k,nodeok)
  end
  nagios_exit(controller.length,nodeok,cfg)
end

# vi:ft=ruby
